"""Every enumerated value in the domain, in one place."""

from __future__ import annotations

from enum import StrEnum


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"


class OrgRole(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    MEMBER = "MEMBER"
    VIEWER = "VIEWER"


ROLE_RANK: dict[str, int] = {
    OrgRole.VIEWER: 0,
    OrgRole.MEMBER: 1,
    OrgRole.ADMIN: 2,
    OrgRole.OWNER: 3,
}


class EntityKind(StrEnum):
    BUYER = "BUYER"
    SELLER = "SELLER"


class DealState(StrEnum):
    DRAFT = "DRAFT"
    TERMS_SIGNED = "TERMS_SIGNED"
    FUNDED = "FUNDED"
    IN_PROGRESS = "IN_PROGRESS"
    DISPUTED = "DISPUTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"


class MilestoneState(StrEnum):
    PENDING = "PENDING"
    EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED"
    VERIFYING = "VERIFYING"
    RELEASE_APPROVED = "RELEASE_APPROVED"
    UNDER_HUMAN_REVIEW = "UNDER_HUMAN_REVIEW"
    REJECTED = "REJECTED"
    SETTLED = "SETTLED"
    DISPUTED = "DISPUTED"


class Decision(StrEnum):
    RELEASE = "RELEASE"
    REJECT = "REJECT"
    ESCALATE = "ESCALATE"


class ClauseVerdictValue(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNVERIFIABLE = "UNVERIFIABLE"


class ClauseKind(StrEnum):
    ARTIFACT_PRESENT = "ARTIFACT_PRESENT"
    DATE_WITHIN = "DATE_WITHIN"
    AMOUNT_AT_LEAST = "AMOUNT_AT_LEAST"
    QUANTITY_AT_LEAST = "QUANTITY_AT_LEAST"
    FIELD_EQUALS = "FIELD_EQUALS"
    FIELD_MATCHES_SPEC = "FIELD_MATCHES_SPEC"
    VISUAL_CONSISTENT_WITH = "VISUAL_CONSISTENT_WITH"


class ArtifactType(StrEnum):
    INVOICE = "INVOICE"
    GRN = "GRN"
    PHOTO_SET = "PHOTO_SET"
    DELIVERY_CHALLAN = "DELIVERY_CHALLAN"
    CONDITION_REPORT = "CONDITION_REPORT"
    SPEC_REFERENCE = "SPEC_REFERENCE"


class Direction(StrEnum):
    RELEASE = "RELEASE"
    REFUND = "REFUND"


class AuthorizedBy(StrEnum):
    ENGINE = "ENGINE"
    HUMAN = "HUMAN"


class PayoutStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class DisputeOutcome(StrEnum):
    FULL_RELEASE = "FULL_RELEASE"
    PARTIAL = "PARTIAL"
    FULL_REFUND = "FULL_REFUND"


class HumanAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    OVERRIDE = "OVERRIDE"


class NotificationKind(StrEnum):
    DEAL_CREATED = "DEAL_CREATED"
    TERMS_SIGNED = "TERMS_SIGNED"
    DEAL_FUNDED = "DEAL_FUNDED"
    EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    DISPUTE_RAISED = "DISPUTE_RAISED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    PAYOUT_COMPLETED = "PAYOUT_COMPLETED"
    PAYOUT_FAILED = "PAYOUT_FAILED"
    INVITATION_RECEIVED = "INVITATION_RECEIVED"
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"


class LedgerEventType(StrEnum):
    DEAL_CREATED = "DEAL_CREATED"
    DEAL_TRANSITION = "DEAL_TRANSITION"
    MILESTONE_TRANSITION = "MILESTONE_TRANSITION"
    EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED"
    ATTESTATION_WRITTEN = "ATTESTATION_WRITTEN"
    SETTLEMENT_AUTHORIZED = "SETTLEMENT_AUTHORIZED"
    PAYOUT_RECORDED = "PAYOUT_RECORDED"
    PAYOUT_FAILED = "PAYOUT_FAILED"
    HUMAN_DECISION = "HUMAN_DECISION"
    DISPUTE_RAISED = "DISPUTE_RAISED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    CHAIN_ANCHORED = "CHAIN_ANCHORED"
    ILLEGAL_TRANSITION_ATTEMPT = "ILLEGAL_TRANSITION_ATTEMPT"
    THRESHOLD_CHANGED = "THRESHOLD_CHANGED"
    RISK_SCORED = "RISK_SCORED"


class RailMode(StrEnum):
    SIMULATED = "SIMULATED"
    RAZORPAY_TEST = "RAZORPAY_TEST"
