"""I12 -- tenant isolation, enumerated from the application rather than by hand.

The route list comes from the generated OpenAPI document, so a new tenant-owned
route added without scoping fails this suite automatically.  It is not a list
somebody has to remember to update.

Cross-tenant reads return **404, not 403**, so ids cannot be probed.
"""

from __future__ import annotations

import re
import uuid
from typing import Any

import httpx
import pytest
from asgi_lifespan import LifespanManager  # type: ignore[import-not-found]

from tests.conftest import requires_db

pytestmark = requires_db


# Routes that are deliberately not tenant-scoped, each with the reason.
PUBLIC_ROUTES: dict[str, str] = {
    "/": "service banner",
    "/docs": "openapi ui",
    "/docs/oauth2-redirect": "openapi ui callback",
    "/redoc": "openapi ui",
    "/openapi.json": "openapi document",
    "/api/v1/auth/register": "creating an account precedes having a tenant",
    "/api/v1/auth/login": "ditto",
    "/api/v1/auth/refresh": "ditto",
    "/api/v1/auth/logout": "session-scoped, not tenant-scoped",
    "/api/v1/auth/verify-email": "token-scoped",
    "/api/v1/auth/resend-verification": "email-scoped, identical response either way",
    "/api/v1/auth/forgot-password": "email-scoped, identical response either way",
    "/api/v1/auth/reset-password": "token-scoped",
    "/api/v1/auth/change-password": "user-scoped",
    "/api/v1/auth/me": "user-scoped; returns only the caller's own memberships",
    "/api/v1/auth/preferences": "user-scoped",
    "/api/v1/users/me": "user-scoped",
    "/api/v1/organizations": "lists only the caller's own memberships",
    "/api/v1/organizations/current": "resolves the caller's active org",
    "/api/v1/organizations/invitations/accept": "token-scoped by design",
    "/api/v1/evidence/verify": "public Merkle verification of a supplied proof",
    "/api/v1/evidence/download/{token}": "HMAC presigned, short-lived",
    "/api/v1/payments/rail": "the rail disclosure table; no tenant data",
    "/api/v1/payments/webhooks/razorpay": "signature-authenticated provider callback",
    "/api/v1/provenance/tamper-check": "hashes bytes supplied in the request",
    "/api/v1/health/live": "liveness",
    "/api/v1/health/ready": "readiness",
    "/api/v1/health/metrics": "aggregate counters, no tenant rows",
    "/api/v1/dev/assume": "DEMO_MODE-only; issues a real session via the login path",
    "/api/v1/dev/state": "DEMO_MODE-only configuration disclosure",
    # A counterparty passport is the public trading record the other side needs
    # before agreeing to a deal.  It carries no deal contents, no evidence and
    # no member identities.  Documented in docs/SECURITY.md.
    "/api/v1/reputation/entities/{entity_id}": "public counterparty passport",
    "/api/v1/health/eval-summary": (
        "deliberately public: the landing page reads the measured eval headline "
        "before anyone signs in, and it contains no tenant data"
    ),
}

PATH_PARAM = re.compile(r"\{([a-z_]+)\}")


VERBS = ("get", "post", "put", "patch", "delete")

# Every `/api/v1` operation the service exposes.  Below this, the enumeration is
# not doing its job -- see `test_the_route_enumeration_is_not_empty`.
MIN_EXPECTED_ROUTES = 60


def all_routes() -> list[tuple[str, str]]:
    """Every route, taken from the OpenAPI document rather than `app.routes`.

    `app.routes` looked like the obvious source and was the wrong one: FastAPI
    0.141 wraps each `include_router` call in an `_IncludedRouter` that exposes
    no `path`, so walking it yielded only the five app-level routes and this
    entire suite asserted `[] == []`. It was green while proving nothing --
    exactly the failure mode it exists to prevent.

    The OpenAPI document is generated by FastAPI's own introspection and lists
    every path and method, so a router added without scoping still shows up here.
    """
    from app.main import app

    out: list[tuple[str, str]] = []
    for path, operations in app.openapi()["paths"].items():
        for method in operations:
            if method.lower() in VERBS:
                out.append((method.upper(), path))
    return sorted(set(out))


def tenant_routes() -> list[tuple[str, str]]:
    return [(m, p) for m, p in all_routes() if p not in PUBLIC_ROUTES]


def test_the_route_enumeration_is_not_empty() -> None:
    """The guard on the guard.

    Every other test in this module iterates `tenant_routes()`. If that list is
    ever empty they all pass without touching the application, which is how this
    suite silently stopped testing anything. This is the assertion that makes
    that impossible to miss.
    """
    routes = all_routes()
    assert len(routes) >= MIN_EXPECTED_ROUTES, (
        f"only {len(routes)} routes enumerated; the walk is broken, not the app"
    )
    scoped = tenant_routes()
    assert len(scoped) >= MIN_EXPECTED_ROUTES - len(PUBLIC_ROUTES), (
        f"only {len(scoped)} tenant routes after exemptions"
    )
    # Two routes that return a nullable body, and so once answered 200/null to an
    # outsider instead of 404.  They must be in the enumeration.
    assert ("GET", "/api/v1/verification/milestones/{milestone_id}") in scoped
    assert ("GET", "/api/v1/evidence/milestones/{milestone_id}/bundle") in scoped


@pytest.fixture
async def client() -> Any:
    from app.main import app

    async with LifespanManager(app):
        transport = httpx.ASGITransport(app=app)
        async with httpx.AsyncClient(transport=transport, base_url="http://testserver") as c:
            yield c


async def login(client: httpx.AsyncClient, email: str, password: str) -> str:
    response = await client.post("/api/v1/auth/login", json={"email": email, "password": password})
    assert response.status_code == 200, response.text
    return response.json()["access_token"]


@pytest.fixture
async def tenants(client: httpx.AsyncClient, parties: dict[str, Any]) -> dict[str, Any]:
    """Two real sessions plus a deal, an evidence bundle and an attestation
    belonging to the first tenant."""
    from sqlalchemy import select

    from app.db.session import get_session_factory
    from app.models.commerce import Milestone
    from tests.factories import make_deal, submit_evidence, verify_milestone

    async with get_session_factory()() as session:
        deal = await make_deal(session, parties)
        milestone = (
            await session.execute(
                select(Milestone).where(Milestone.deal_id == deal.id, Milestone.seq == 2)
            )
        ).scalar_one()
        bundle = await submit_evidence(
            session,
            deal,
            milestone,
            org_id=parties["seller_org_id"],
            user_id=parties["seller_user_id"],
            folder="production",
        )
        attestation, _ = await verify_milestone(session, deal, milestone, bundle)
        from app.models.commerce import Artifact

        artifact = (
            await session.execute(select(Artifact).where(Artifact.bundle_id == bundle.id).limit(1))
        ).scalar_one()
        dispute_id = uuid.uuid4()

    owner_token = await login(client, "buyer@aegistest.dev", parties["password"])
    outsider_token = await login(client, "outsider@aegistest.dev", parties["password"])
    return {
        "owner_token": owner_token,
        "outsider_token": outsider_token,
        "ids": {
            "deal_id": str(deal.id),
            "milestone_id": str(milestone.id),
            "bundle_id": str(bundle.id),
            "artifact_id": str(artifact.id),
            "attestation_id": str(attestation.id),
            "dispute_id": str(dispute_id),
            "entity_id": str(parties["seller_entity_id"]),
            "org_id": str(parties["buyer_org_id"]),
            "user_id": str(parties["buyer_user_id"]),
            "token": "not-a-real-token",
        },
    }


def fill(path: str, ids: dict[str, str]) -> str:
    def substitute(match: re.Match[str]) -> str:
        name = match.group(1)
        return ids.get(name, str(uuid.uuid4()))

    return PATH_PARAM.sub(substitute, path)


BODIES: dict[str, dict[str, Any]] = {
    "POST /api/v1/deals": {
        "title": "x",
        "total_paise": 100,
        "seller_org_slug": "nope",
        "milestones": [
            {
                "seq": 1,
                "title": "m",
                "amount_paise": 100,
                "verification_condition": {"clauses": [], "required_artifact_types": []},
            }
        ],
    },
    "POST /api/v1/deals/{deal_id}/sign-terms": {"accept": True},
    "POST /api/v1/deals/{deal_id}/fund": {},
    "POST /api/v1/deals/{deal_id}/cancel": {"reason": "a written reason here"},
    "POST /api/v1/milestones/{milestone_id}/human-review": {
        "action": "APPROVE",
        "reason": "a written reason here",
    },
    "POST /api/v1/milestones/{milestone_id}/disputes": {"claim": "a written claim here"},
    "POST /api/v1/disputes/{dispute_id}/counter-claim": {
        "counter_claim": "a written counter claim"
    },
    "POST /api/v1/disputes/{dispute_id}/resolve": {
        "release_paise": 1,
        "refund_paise": 0,
        "reason": "a written reason here",
    },
    "POST /api/v1/chat/deals/{deal_id}": {"body": "hello"},
    "POST /api/v1/notifications/mark-read": {"ids": None},
    "PUT /api/v1/notifications/preferences": {
        "kind": "DEAL_FUNDED",
        "in_app": True,
        "email": False,
    },
    "POST /api/v1/organizations": {"name": "New Org"},
    "POST /api/v1/organizations/invitations": {"email": "x@y.z", "role": "MEMBER"},
    "PATCH /api/v1/organizations/members/{user_id}/role": {"role": "MEMBER"},
    "POST /api/v1/entities": {"kind": "SELLER", "display_name": "e"},
}

# SSE endpoints hold the connection open; they are covered by a dedicated test.
STREAMING = ("/api/v1/realtime/",)


def test_the_route_inventory_is_complete():
    """Every route is either classified public with a reason, or tenant-scoped."""
    routes = all_routes()
    assert routes, "no routes discovered -- the app failed to import"
    unclassified = [p for _, p in routes if p not in PUBLIC_ROUTES and not p.startswith("/api/v1")]
    assert unclassified == [], f"routes outside /api/v1 must be classified: {unclassified}"
    for path, reason in PUBLIC_ROUTES.items():
        assert reason, f"{path} is exempt without a reason"


@pytest.mark.asyncio
async def test_no_tenant_route_answers_without_authentication(client, tenants):
    """A request with no session at all must not be answered.

    The sweep runs on its own cookie-free client.  Sharing the `client` fixture
    looked harmless and was not: `httpx.AsyncClient` persists cookies, so the
    `tenants` fixture's logins left a live session cookie on it and every
    "unauthenticated" request was quietly authenticated.
    """
    from app.main import app

    failures = []
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://testserver") as anonymous:
        for method, path in tenant_routes():
            if any(path.startswith(prefix) for prefix in STREAMING):
                continue
            url = fill(path, tenants["ids"])
            body = BODIES.get(f"{method} {path}")
            response = await anonymous.request(method, url, json=body)
            assert not response.cookies, "the anonymous client must stay anonymous"
            if response.status_code not in (401, 403, 404, 405, 422):
                failures.append((method, path, response.status_code))
    assert failures == [], f"answered unauthenticated: {failures}"


@pytest.mark.asyncio
async def test_cross_tenant_access_is_refused_on_every_tenant_route(client, tenants):
    """The heart of I12.  An outsider with a perfectly valid session and a
    correct id must never see another organization's data."""
    headers = {"Authorization": f"Bearer {tenants['outsider_token']}"}
    leaks = []
    for method, path in tenant_routes():
        if any(path.startswith(prefix) for prefix in STREAMING):
            continue
        if "{" not in path:
            # Collection routes are scoped by the caller's own org; a separate
            # assertion below checks they return nothing belonging to the owner.
            continue
        url = fill(path, tenants["ids"])
        body = BODIES.get(f"{method} {path}")
        response = await client.request(method, url, json=body, headers=headers)
        if response.status_code < 400:
            leaks.append((method, path, response.status_code, response.text[:160]))
        elif response.status_code == 403 and method == "GET":
            # A read of another tenant's resource must be 404, not 403: a 403
            # confirms the id exists.
            leaks.append((method, path, 403, "403 leaks existence; expected 404"))
    assert leaks == [], f"cross-tenant leaks: {leaks}"


@pytest.mark.asyncio
async def test_collection_routes_return_only_the_callers_own_rows(client, tenants):
    owner = {"Authorization": f"Bearer {tenants['owner_token']}"}
    outsider = {"Authorization": f"Bearer {tenants['outsider_token']}"}

    owned = await client.get("/api/v1/deals", headers=owner)
    assert owned.status_code == 200
    assert len(owned.json()) >= 1

    others = await client.get("/api/v1/deals", headers=outsider)
    assert others.status_code == 200
    assert others.json() == []

    queue = await client.get("/api/v1/milestones/review-queue", headers=outsider)
    assert queue.status_code == 200
    assert queue.json() == []

    disputes = await client.get("/api/v1/disputes", headers=outsider)
    assert disputes.status_code == 200
    assert disputes.json() == []


@pytest.mark.asyncio
async def test_the_owner_can_read_what_the_outsider_cannot(client, tenants):
    """Otherwise the previous test would pass with a broken application."""
    headers = {"Authorization": f"Bearer {tenants['owner_token']}"}
    ids = tenants["ids"]
    for url in (
        f"/api/v1/deals/{ids['deal_id']}",
        f"/api/v1/deals/{ids['deal_id']}/timeline",
        f"/api/v1/milestones/{ids['milestone_id']}",
        f"/api/v1/verification/attestations/{ids['attestation_id']}",
        f"/api/v1/provenance/attestations/{ids['attestation_id']}",
        f"/api/v1/ledger/deals/{ids['deal_id']}",
        f"/api/v1/ledger/deals/{ids['deal_id']}/verify",
        f"/api/v1/evidence/artifacts/{ids['artifact_id']}/proof",
        f"/api/v1/chat/deals/{ids['deal_id']}",
    ):
        response = await client.get(url, headers=headers)
        assert response.status_code == 200, f"{url} -> {response.status_code} {response.text[:200]}"


@pytest.mark.asyncio
async def test_id_guessing_returns_404_not_403(client, tenants):
    headers = {"Authorization": f"Bearer {tenants['outsider_token']}"}
    for url in (
        f"/api/v1/deals/{tenants['ids']['deal_id']}",
        f"/api/v1/milestones/{tenants['ids']['milestone_id']}",
        f"/api/v1/verification/attestations/{tenants['ids']['attestation_id']}",
        f"/api/v1/ledger/deals/{tenants['ids']['deal_id']}",
    ):
        response = await client.get(url, headers=headers)
        assert response.status_code == 404, f"{url} -> {response.status_code}"
        assert response.json()["error"]["code"] == "NOT_FOUND"


@pytest.mark.asyncio
async def test_a_random_id_and_a_real_id_are_indistinguishable(client, tenants):
    """If a real-but-foreign id 403s and a nonexistent id 404s, the id space is
    enumerable.  Both must answer identically."""
    headers = {"Authorization": f"Bearer {tenants['outsider_token']}"}
    real = await client.get(f"/api/v1/deals/{tenants['ids']['deal_id']}", headers=headers)
    fake = await client.get(f"/api/v1/deals/{uuid.uuid4()}", headers=headers)
    assert real.status_code == fake.status_code == 404
    assert real.json()["error"]["code"] == fake.json()["error"]["code"]


@pytest.mark.asyncio
async def test_repository_layer_refuses_an_unregistered_model():
    """I12 is architectural: there is no unscoped accessor for a tenant type, and
    asking for one that was never registered raises rather than returning rows."""
    from app.db.repo import TenantRepo
    from app.db.session import get_session_factory
    from app.models.identity import User

    async with get_session_factory()() as session:
        repo = TenantRepo(session, uuid.uuid4())
        with pytest.raises(TypeError):
            repo.scoped(User)


@pytest.mark.asyncio
async def test_repository_requires_an_org_id():
    from app.db.repo import TenantRepo
    from app.db.session import get_session_factory

    async with get_session_factory()() as session:
        with pytest.raises(ValueError):
            TenantRepo(session, None)  # type: ignore[arg-type]
