"""initial schema

Creates every table, plus the two things application code cannot guarantee:

* the money-conservation CHECK on ``deals`` (I4), generated from the model; and
* ``BEFORE UPDATE OR DELETE`` triggers that make ``attestations`` and
  ``ledger_events`` append-only (spec 7).  A code convention is not an acceptable
  guarantee for immutability, so the database raises.

Revision ID: 8acfd7db4b04
Revises: 
Create Date: 2026-09-04 16:20:53.793899
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8acfd7db4b04'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_records'))
    )
    op.create_index(op.f('ix_audit_records_created_at'), 'audit_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_records_org_id'), 'audit_records', ['org_id'], unique=False)
    op.create_table('dead_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('consumer_group', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('drained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letters'))
    )
    op.create_table('idempotency_records',
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('result_ref', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', name=op.f('pk_idempotency_records'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=40), nullable=False),
    sa.Column('aggregate_id', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('event_id', name='event_id')
    )
    op.create_index('ix_outbox_unpublished', 'outbox_events', ['published_at', 'id'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('consumer_group', sa.String(length=40), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'consumer_group', name=op.f('pk_processed_events'))
    )
    op.create_table('risk_model_artifacts',
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_names_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_path', sa.String(length=400), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('pk_risk_model_artifacts'))
    )
    op.create_table('seed_checkpoints',
    sa.Column('step_name', sa.String(length=80), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('step_name', name=op.f('pk_seed_checkpoints'))
    )
    op.create_table('token_spends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_write_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_spends'))
    )
    op.create_index(op.f('ix_token_spends_created_at'), 'token_spends', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='userstatus', native_enum=False, length=20), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('active_org_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email_normalized', name=op.f('uq_users_email_normalized'))
    )
    op.create_table('webhook_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_receipts')),
    sa.UniqueConstraint('provider', 'external_id', name='provider_external')
    )
    op.create_table('email_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_tokens_token_hash'))
    )
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('BUYER', 'SELLER', name='entitykind', native_enum=False, length=10), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('pubkey', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_entities_org_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_org_id'), 'entities', ['org_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='orgrole', native_enum=False, length=10), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invitations_invited_by')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_invitations_org_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    op.create_index(op.f('ix_invitations_org_id'), 'invitations', ['org_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', 'kind', name='user_kind')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='orgrole', native_enum=False, length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_organization_members_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('org_id', 'user_id', name='org_user')
    )
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('counterparty_profiles',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('deals_completed', sa.BigInteger(), nullable=False),
    sa.Column('gmv_paise', sa.BigInteger(), nullable=False),
    sa.Column('disputes_raised', sa.BigInteger(), nullable=False),
    sa.Column('disputes_lost', sa.BigInteger(), nullable=False),
    sa.Column('on_time_rate', sa.Float(), nullable=False),
    sa.Column('largest_deal_paise', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('score_version', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_counterparty_profiles_entity_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_counterparty_profiles'))
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('org_id_buyer', sa.UUID(), nullable=False),
    sa.Column('org_id_seller', sa.UUID(), nullable=False),
    sa.Column('buyer_entity_id', sa.UUID(), nullable=False),
    sa.Column('seller_entity_id', sa.UUID(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'TERMS_SIGNED', 'FUNDED', 'IN_PROGRESS', 'DISPUTED', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'EXPIRED', name='dealstate', native_enum=False, length=20), nullable=False),
    sa.Column('terms_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terms_hash', sa.String(length=64), nullable=False),
    sa.Column('dispute_window_days', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('chain_deal_id', sa.String(length=66), nullable=True),
    sa.Column('chain_tx', sa.String(length=66), nullable=True),
    sa.Column('funded_paise', sa.BigInteger(), nullable=False),
    sa.Column('released_paise', sa.BigInteger(), nullable=False),
    sa.Column('refunded_paise', sa.BigInteger(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing_tier', sa.String(length=20), nullable=True),
    sa.Column('funding_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('released_paise >= 0 AND refunded_paise >= 0 AND funded_paise >= 0 AND total_paise > 0 AND released_paise + refunded_paise <= funded_paise', name=op.f('ck_deals_money_conservation')),
    sa.ForeignKeyConstraint(['buyer_entity_id'], ['entities.id'], name=op.f('fk_deals_buyer_entity_id')),
    sa.ForeignKeyConstraint(['org_id_buyer'], ['organizations.id'], name=op.f('fk_deals_org_id_buyer')),
    sa.ForeignKeyConstraint(['org_id_seller'], ['organizations.id'], name=op.f('fk_deals_org_id_seller')),
    sa.ForeignKeyConstraint(['seller_entity_id'], ['entities.id'], name=op.f('fk_deals_seller_entity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals')),
    sa.UniqueConstraint('reference', name=op.f('uq_deals_reference'))
    )
    op.create_index(op.f('ix_deals_created_at'), 'deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_deals_org_id_buyer'), 'deals', ['org_id_buyer'], unique=False)
    op.create_index(op.f('ix_deals_org_id_seller'), 'deals', ['org_id_seller'], unique=False)
    op.create_index('ix_deals_parties', 'deals', ['org_id_buyer', 'org_id_seller'], unique=False)
    op.create_table('chain_anchors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('milestone_seq', sa.Integer(), nullable=True),
    sa.Column('attestation_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_chain_anchors_deal_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_anchors'))
    )
    op.create_index(op.f('ix_chain_anchors_deal_id'), 'chain_anchors', ['deal_id'], unique=False)
    op.create_table('deal_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_by_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_messages_deal_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_deal_messages_sender_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_messages'))
    )
    op.create_index(op.f('ix_deal_messages_created_at'), 'deal_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_deal_messages_deal_id'), 'deal_messages', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_messages_org_id'), 'deal_messages', ['org_id'], unique=False)
    op.create_table('ledger_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_anchor_tx', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_ledger_events_deal_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_events')),
    sa.UniqueConstraint('seq', name=op.f('uq_ledger_events_seq'))
    )
    op.create_index('ix_ledger_deal_seq', 'ledger_events', ['deal_id', 'seq'], unique=False)
    op.create_index(op.f('ix_ledger_events_created_at'), 'ledger_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_events_deal_id'), 'ledger_events', ['deal_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_org_id'), 'ledger_events', ['org_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'EVIDENCE_SUBMITTED', 'VERIFYING', 'RELEASE_APPROVED', 'UNDER_HUMAN_REVIEW', 'REJECTED', 'SETTLED', 'DISPUTED', name='milestonestate', native_enum=False, length=24), nullable=False),
    sa.Column('verification_condition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paise > 0', name=op.f('ck_milestones_amount_positive')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_milestones_deal_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones')),
    sa.UniqueConstraint('deal_id', 'seq', name='deal_seq')
    )
    op.create_index(op.f('ix_milestones_deal_id'), 'milestones', ['deal_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_user_id', sa.UUID(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('counter_claim', sa.Text(), nullable=True),
    sa.Column('arbiter_recommendation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_decided_by', sa.UUID(), nullable=True),
    sa.Column('human_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_delta_paise', sa.BigInteger(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_disputes_deal_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['human_decided_by'], ['users.id'], name=op.f('fk_disputes_human_decided_by')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_disputes_milestone_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], name=op.f('fk_disputes_raised_by_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    op.create_index(op.f('ix_disputes_deal_id'), 'disputes', ['deal_id'], unique=False)
    op.create_index(op.f('ix_disputes_milestone_id'), 'disputes', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_disputes_org_id'), 'disputes', ['org_id'], unique=False)
    op.create_table('evidence_bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_evidence_bundles_milestone_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_evidence_bundles_submitted_by_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_bundles'))
    )
    op.create_index(op.f('ix_evidence_bundles_milestone_id'), 'evidence_bundles', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_evidence_bundles_org_id'), 'evidence_bundles', ['org_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['evidence_bundles.id'], name=op.f('fk_artifacts_bundle_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_bundle_id'), 'artifacts', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_artifacts_org_id'), 'artifacts', ['org_id'], unique=False)
    op.create_index(op.f('ix_artifacts_sha256'), 'artifacts', ['sha256'], unique=False)
    op.create_table('attestations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('RELEASE', 'REJECT', 'ESCALATE', name='decision', native_enum=False, length=12), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clause_verdicts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_merkle_root', sa.String(length=64), nullable=False),
    sa.Column('deterministic_prechecks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calibration_version', sa.String(length=20), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=200), nullable=False),
    sa.Column('signer_key_id', sa.String(length=60), nullable=False),
    sa.Column('signer_address', sa.String(length=50), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('chain_tx', sa.String(length=66), nullable=True),
    sa.Column('chain_block', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_attestations_confidence_range')),
    sa.ForeignKeyConstraint(['bundle_id'], ['evidence_bundles.id'], name=op.f('fk_attestations_bundle_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_attestations_milestone_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attestations'))
    )
    op.create_index(op.f('ix_attestations_created_at'), 'attestations', ['created_at'], unique=False)
    op.create_index(op.f('ix_attestations_milestone_id'), 'attestations', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_attestations_org_id'), 'attestations', ['org_id'], unique=False)
    op.create_table('settlement_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('attestation_id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('RELEASE', 'REFUND', name='direction', native_enum=False, length=10), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('authorized_by', sa.Enum('ENGINE', 'HUMAN', name='authorizedby', native_enum=False, length=10), nullable=False),
    sa.Column('authorized_by_user_id', sa.UUID(), nullable=True),
    sa.Column('human_approved', sa.Boolean(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_paise > 0', name=op.f('ck_settlement_authorizations_amount_positive')),
    sa.ForeignKeyConstraint(['attestation_id'], ['attestations.id'], name=op.f('fk_settlement_authorizations_attestation_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_settlement_authorizations_deal_id')),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_settlement_authorizations_dispute_id')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_settlement_authorizations_milestone_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_authorizations'))
    )
    op.create_index(op.f('ix_settlement_authorizations_deal_id'), 'settlement_authorizations', ['deal_id'], unique=False)
    op.create_index(op.f('ix_settlement_authorizations_idempotency_key'), 'settlement_authorizations', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_settlement_authorizations_milestone_id'), 'settlement_authorizations', ['milestone_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('authorization_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('RELEASE', 'REFUND', name='direction', native_enum=False, length=10), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('rail', sa.String(length=20), nullable=False),
    sa.Column('rail_ref', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='payoutstatus', native_enum=False, length=12), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('chain_tx', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paise > 0', name=op.f('ck_payouts_amount_positive')),
    sa.ForeignKeyConstraint(['authorization_id'], ['settlement_authorizations.id'], name=op.f('fk_payouts_authorization_id')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_payouts_deal_id')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_payouts_milestone_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts')),
    sa.UniqueConstraint('idempotency_key', name='idempotency_key')
    )
    op.create_index(op.f('ix_payouts_created_at'), 'payouts', ['created_at'], unique=False)
    op.create_index(op.f('ix_payouts_deal_id'), 'payouts', ['deal_id'], unique=False)
    op.create_index(op.f('ix_payouts_milestone_id'), 'payouts', ['milestone_id'], unique=False)


    # ── Append-only enforcement (spec 7) ────────────────────────────────────
    # A correction to an attestation is a NEW row that supersedes the old one; a
    # ledger event is never edited, because that is what makes the hash chain mean
    # anything.  Both are enforced here, in the database, not by convention.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION aegis_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'append-only table %: % is not permitted (aegis attestation immutability)',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER attestations_append_only
        BEFORE UPDATE OR DELETE ON attestations
        FOR EACH ROW EXECUTE FUNCTION aegis_append_only();
        """
    )
    # The chain-anchoring tx is stamped onto a ledger event after the fact, which
    # is the single legitimate mutation.  It is allowed only for that one column
    # and only while it is still NULL; everything else raises (I5).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION aegis_ledger_guard() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'ledger_events is append-only: DELETE is not permitted'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF (OLD.id, OLD.seq, OLD.deal_id, OLD.org_id, OLD.event_type, OLD.actor,
                OLD.reason, OLD.payload_json, OLD.payload_hash, OLD.prev_hash, OLD.created_at)
               IS DISTINCT FROM
               (NEW.id, NEW.seq, NEW.deal_id, NEW.org_id, NEW.event_type, NEW.actor,
                NEW.reason, NEW.payload_json, NEW.payload_hash, NEW.prev_hash, NEW.created_at)
            THEN
                RAISE EXCEPTION
                    'ledger_events is append-only: only chain_anchor_tx may be stamped'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF OLD.chain_anchor_tx IS NOT NULL
               AND OLD.chain_anchor_tx IS DISTINCT FROM NEW.chain_anchor_tx THEN
                RAISE EXCEPTION 'ledger_events.chain_anchor_tx is write-once'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER ledger_events_append_only
        BEFORE UPDATE OR DELETE ON ledger_events
        FOR EACH ROW EXECUTE FUNCTION aegis_ledger_guard();
        """
    )
    # ### end append-only enforcement ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS ledger_events_append_only ON ledger_events;")
    op.execute("DROP TRIGGER IF EXISTS attestations_append_only ON attestations;")
    op.execute("DROP FUNCTION IF EXISTS aegis_ledger_guard();")
    op.execute("DROP FUNCTION IF EXISTS aegis_append_only();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_milestone_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_deal_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_created_at'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_settlement_authorizations_milestone_id'), table_name='settlement_authorizations')
    op.drop_index(op.f('ix_settlement_authorizations_idempotency_key'), table_name='settlement_authorizations')
    op.drop_index(op.f('ix_settlement_authorizations_deal_id'), table_name='settlement_authorizations')
    op.drop_table('settlement_authorizations')
    op.drop_index(op.f('ix_attestations_org_id'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_milestone_id'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_created_at'), table_name='attestations')
    op.drop_table('attestations')
    op.drop_index(op.f('ix_artifacts_sha256'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_org_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_bundle_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_evidence_bundles_org_id'), table_name='evidence_bundles')
    op.drop_index(op.f('ix_evidence_bundles_milestone_id'), table_name='evidence_bundles')
    op.drop_table('evidence_bundles')
    op.drop_index(op.f('ix_disputes_org_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_milestone_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_deal_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_milestones_deal_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_ledger_events_org_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_deal_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_created_at'), table_name='ledger_events')
    op.drop_index('ix_ledger_deal_seq', table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_index(op.f('ix_deal_messages_org_id'), table_name='deal_messages')
    op.drop_index(op.f('ix_deal_messages_deal_id'), table_name='deal_messages')
    op.drop_index(op.f('ix_deal_messages_created_at'), table_name='deal_messages')
    op.drop_table('deal_messages')
    op.drop_index(op.f('ix_chain_anchors_deal_id'), table_name='chain_anchors')
    op.drop_table('chain_anchors')
    op.drop_index('ix_deals_parties', table_name='deals')
    op.drop_index(op.f('ix_deals_org_id_seller'), table_name='deals')
    op.drop_index(op.f('ix_deals_org_id_buyer'), table_name='deals')
    op.drop_index(op.f('ix_deals_created_at'), table_name='deals')
    op.drop_table('deals')
    op.drop_table('counterparty_profiles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_invitations_org_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_entities_org_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_table('webhook_receipts')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_spends_created_at'), table_name='token_spends')
    op.drop_table('token_spends')
    op.drop_table('seed_checkpoints')
    op.drop_table('risk_model_artifacts')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_unpublished', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('organizations')
    op.drop_table('idempotency_records')
    op.drop_table('dead_letters')
    op.drop_index(op.f('ix_audit_records_org_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_created_at'), table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
