"""settlement authorization claim

Adds the column that serialises I6 in the database rather than in Redis.

Before this, twenty concurrent deliveries of one ``settlement.authorized`` event
each reached the payment rail; the unique index on ``payouts.idempotency_key``
still guaranteed one payout, but the rail saw twenty transfer requests.  Relying
on the provider's own idempotency for that is not a guarantee this system can
make.  ``claimed_at`` is now taken by an atomic conditional UPDATE before the
rail call, so exactly one worker reaches the rail -- with Redis up or down.

Revision ID: 917318905b2d
Revises: 8acfd7db4b04
Create Date: 2026-09-04 16:29:29.045494
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '917318905b2d'
down_revision: str | None = '8acfd7db4b04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlement_authorizations', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlement_authorizations', 'claimed_at')
    # ### end Alembic commands ###
